[build]
  command = "npm run build"
  functions = ".netlify/functions/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/redirect"

[[redirects]]
  from = "/:code"
  to = "/.netlify/functions/redirect/:code"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
